# Generated by Django 4.0.5 on 2022-06-03 13:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mguides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('distance_from_Nairobi', models.IntegerField(blank=True)),
                ('trail_length', models.IntegerField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('departure_time', models.TimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('rendezvous_point', models.CharField(max_length=100)),
                ('difficulty_mode', models.CharField(max_length=100)),
                ('date_of_hike', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('mguide', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mguides.mguide')),
            ],
        ),
    ]
